sudo: required
dist: trusty

services:
  - docker

matrix:
  fast_finish: true

before_script:
  - make build

script:
  - make test

after_success:
  - if [[ "${TRAVIS_TAG}" != "" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push udovicic/magentost:${TRAVIS_TAG};
    fi
