language: php
php:
  - 7.3

services:
  - docker

matrix:
  fast_finish: true

before_script:
  - make build

script:
  - make test

after_success:
  - if [[ "${TRAVIS_TAG}" != "" ]]; then
    GENERAL_VERSION=`grep "version" toolset/composer.json | awk -F ":" '{ print $2 }' | sed 's/[", ]//g' | sed -r 's/[^0-9]+([0-9]*).[^0-9]+([0-9]*)/\1.\2/'`;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push udovicic/magentost:${TRAVIS_TAG};
    docker tag udovicic/magentost:${TRAVIS_TAG} udovicic/magentost:latest;
    docker push udovicic/magentost:latest;
    docker tag udovicic/magentost:${TRAVIS_TAG} udovicic/magentost:${GENERAL_VERSION};
    docker push udovicic/magentost:${GENERAL_VERSION};
    fi
